//
// Created by yusuke on 2019-04-28.
//

#ifndef BINARY_SEARCH_TREE_BINARY_SEARCH_TREE_H
#define BINARY_SEARCH_TREE_BINARY_SEARCH_TREE_H

int tree_main();

#endif //BINARY_SEARCH_TREE_BINARY_SEARCH_TREE_H
