//
// Created by yusuke on 2019-05-03.
//

#ifndef DYNAMIC_PROGRAMMING_LARGEST_RECTANGLE_H
#define DYNAMIC_PROGRAMMING_LARGEST_RECTANGLE_H

void lr_main();

#endif //DYNAMIC_PROGRAMMING_LARGEST_RECTANGLE_H
