//
// Created by yusuke on 2019-05-03.
//

#ifndef DYNAMIC_PROGRAMMING_LONGEST_INCREASING_SUBSEQUENCE_H
#define DYNAMIC_PROGRAMMING_LONGEST_INCREASING_SUBSEQUENCE_H

void lis_main();

#endif //DYNAMIC_PROGRAMMING_LONGEST_INCREASING_SUBSEQUENCE_H
